/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.system.view;

import hotel.system.controller.CustomerController;
import hotel.system.controller.PackageController;
import hotel.system.controller.ReservationController;
import hotel.system.controller.RoomController;
import hotel.system.dto.CustomerDto;
import hotel.system.dto.PackageDto;
import hotel.system.dto.ReservationDetailsDto;
import hotel.system.dto.RoomDto;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuneth Perera
 */
public class ReservationCancelView extends javax.swing.JFrame {
    
    private ReservationController reservationController;
    private CustomerController customerController;
    private RoomController roomController;
    private PackageController packageController;
    
    private List<ReservationDetailsDto> reservationDetailsDtos = new ArrayList<>();

    /**
     * Creates new form ReservationCancelView
     */
    public ReservationCancelView(ReservationDetailsDto selectedReservationDetailsDto) {
        initComponents();
        customerController = new CustomerController();
            roomController = new RoomController();
            packageController = new PackageController();
        reservationController = new ReservationController();
        setReservationDetails(selectedReservationDetailsDto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ResIdlbl = new javax.swing.JLabel();
        RoomIdlbl = new javax.swing.JLabel();
        CustIdlbl = new javax.swing.JLabel();
        txtResId = new javax.swing.JTextField();
        CheckInlbl = new javax.swing.JLabel();
        CheckOutlbl = new javax.swing.JLabel();
        Amountlbl = new javax.swing.JLabel();
        RoomDetaillbl = new javax.swing.JLabel();
        btnRoomSearch = new javax.swing.JButton();
        PackageIdlbl = new javax.swing.JLabel();
        CustDetaillbl = new javax.swing.JLabel();
        PackDetaillbl = new javax.swing.JLabel();
        btnCustSearch = new javax.swing.JButton();
        btnPackSearch = new javax.swing.JButton();
        dateCheckIn = new com.toedter.calendar.JDateChooser();
        dateCheckOut = new com.toedter.calendar.JDateChooser();
        btnCancel = new javax.swing.JButton();
        reserStatuslbl = new javax.swing.JLabel();
        TotalAmountlbl = new javax.swing.JLabel();
        CheckInTimelbl = new javax.swing.JLabel();
        txtCheckInTime = new javax.swing.JTextField();
        CheckOutTimelbl = new javax.swing.JLabel();
        txtCheckOutTime = new javax.swing.JTextField();
        txtRoomID = new javax.swing.JTextField();
        txtCustomerID = new javax.swing.JTextField();
        txtReserveStatus = new javax.swing.JTextField();
        txtPackageID = new javax.swing.JTextField();
        btnCancel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 449));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manage Reservation");

        ResIdlbl.setText("Reservation Id");

        RoomIdlbl.setText("Room Id");

        CustIdlbl.setText("Customer Id");

        CheckInlbl.setText("CheckIn Date");

        CheckOutlbl.setText("CheckOut Date");

        Amountlbl.setText("Amount :");

        RoomDetaillbl.setForeground(new java.awt.Color(51, 51, 255));
        RoomDetaillbl.setText("Room Detail........");

        btnRoomSearch.setText("Search");
        btnRoomSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomSearchActionPerformed(evt);
            }
        });

        PackageIdlbl.setText("Package Id");

        CustDetaillbl.setText("Customer Detail.......");

        PackDetaillbl.setForeground(new java.awt.Color(255, 51, 51));
        PackDetaillbl.setText("Package Detail.......");

        btnCustSearch.setText("Search");
        btnCustSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustSearchActionPerformed(evt);
            }
        });

        btnPackSearch.setText("Search");
        btnPackSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackSearchActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCancel.setText("Cancel Reservation");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        reserStatuslbl.setText("Reserve Status");

        TotalAmountlbl.setText("Total Amount......");

        CheckInTimelbl.setText("CheckIn Time");

        CheckOutTimelbl.setText("CheckOut Time");

        txtCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIDActionPerformed(evt);
            }
        });

        btnCancel1.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel1.setText("X");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RoomIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtRoomID)
                                            .addGap(43, 43, 43)
                                            .addComponent(btnRoomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(txtPackageID, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                                .addComponent(txtCustomerID))
                                            .addGap(43, 43, 43)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnCustSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnPackSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtReserveStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(CheckOutlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(dateCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(CheckOutTimelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(txtCheckOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Amountlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(TotalAmountlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(CustDetaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addComponent(RoomDetaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PackDetaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(268, 268, 268)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(273, 273, 273)
                                .addComponent(btnCancel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PackageIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckInlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckInTimelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCheckInTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(reserStatuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancel1)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ResIdlbl)
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RoomIdlbl)
                                            .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtResId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnRoomSearch)
                                            .addComponent(RoomDetaillbl))))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCustSearch)
                                    .addComponent(CustIdlbl)
                                    .addComponent(CustDetaillbl)
                                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PackageIdlbl)
                                    .addComponent(txtPackageID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPackSearch)
                                .addComponent(PackDetaillbl)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(CheckInlbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckOutlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateCheckOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(dateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckInTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckInTimelbl)
                    .addComponent(CheckOutTimelbl)
                    .addComponent(txtCheckOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserStatuslbl)
                    .addComponent(Amountlbl)
                    .addComponent(TotalAmountlbl)
                    .addComponent(txtReserveStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomSearchActionPerformed
        searchRoom();
    }//GEN-LAST:event_btnRoomSearchActionPerformed

    private void btnCustSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustSearchActionPerformed
        searchCustomer();
    }//GEN-LAST:event_btnCustSearchActionPerformed

    private void btnPackSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackSearchActionPerformed
        searchPackage();
    }//GEN-LAST:event_btnPackSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cancelReservation();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIDActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReservationCancelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReservationCancelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReservationCancelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReservationCancelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReservationCancelView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amountlbl;
    private javax.swing.JLabel CheckInTimelbl;
    private javax.swing.JLabel CheckInlbl;
    private javax.swing.JLabel CheckOutTimelbl;
    private javax.swing.JLabel CheckOutlbl;
    private javax.swing.JLabel CustDetaillbl;
    private javax.swing.JLabel CustIdlbl;
    private javax.swing.JLabel PackDetaillbl;
    private javax.swing.JLabel PackageIdlbl;
    private javax.swing.JLabel ResIdlbl;
    private javax.swing.JLabel RoomDetaillbl;
    private javax.swing.JLabel RoomIdlbl;
    private javax.swing.JLabel TotalAmountlbl;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnCustSearch;
    private javax.swing.JButton btnPackSearch;
    private javax.swing.JButton btnRoomSearch;
    private com.toedter.calendar.JDateChooser dateCheckIn;
    private com.toedter.calendar.JDateChooser dateCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel reserStatuslbl;
    private javax.swing.JTextField txtCheckInTime;
    private javax.swing.JTextField txtCheckOutTime;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtPackageID;
    private javax.swing.JTextField txtResId;
    private javax.swing.JTextField txtReserveStatus;
    private javax.swing.JTextField txtRoomID;
    // End of variables declaration//GEN-END:variables

    
    // Method to set details in the view
    private void setReservationDetails(ReservationDetailsDto detailsDto) {

        if (detailsDto != null) {

            String reservationId = detailsDto.getReservationId();
            txtResId.setText(detailsDto.getReservationId());
            System.out.println("ReservationId " + reservationId);

            String roomID = detailsDto.getRoomId();
            txtRoomID.setText(detailsDto.getRoomId());
            System.out.println("RoomID " + roomID);

            String customerID = detailsDto.getCustomerId();
            txtCustomerID.setText(detailsDto.getCustomerId());
            System.out.println("CustID " + customerID);

            String packageID = detailsDto.getPackageId();
            txtPackageID.setText(detailsDto.getPackageId());
            System.out.println("PackID " + packageID);

            dateCheckIn.setDate(detailsDto.getCheckInDate());

            txtCheckInTime.setText(detailsDto.getCheckInTime());

            dateCheckOut.setDate(detailsDto.getCheckOutDate());
            txtCheckOutTime.setText(detailsDto.getCheckOutTime());
            txtReserveStatus.setText(detailsDto.getReserveStatus());
            TotalAmountlbl.setText(String.valueOf(detailsDto.getAmount()));
        }
    }
    
    // cancel reservation
    private void cancelReservation() {
        // Get the reservation ID you want to cancel
        String reservationId = txtResId.getText();

        try {
            // Call the cancelReservation method in the controller
            String resp = reservationController.cancelReservation(reservationId);

            JOptionPane.showMessageDialog(this, resp);
            //generateAutoReserveID();
            //clearFields();
            //getRoomIds();
            //loadTable();
            dispose();
        } catch (Exception ex) {
            // Handle exceptions appropriately
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(ReservationCancelView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    // search Room
    private void searchRoom() {
        String roomId = txtRoomID.getText();
        try {
            RoomDto roomDto = roomController.getRoom(roomId);
            if (roomDto != null) {
                RoomDetaillbl.setText(roomDto.getRoomId() + "   |   " + roomDto.getCategoryId() + "   |   " + roomDto.getRoomNo() + "   |   " + roomDto.getPrice() + "   |   "
                        + roomDto.getAvailabilityStatus());
            } else {
                JOptionPane.showMessageDialog(this, "Room Not Found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(ReservationCancelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // search Customer
    private void searchCustomer() {
        String custId = txtCustomerID.getText();
        try {
            CustomerDto customerDto = customerController.getCustomer(custId);
            if (customerDto != null) {
                CustDetaillbl.setText(customerDto.getCustomerId() + "   |   " + customerDto.getFirstName() + "   |   " + customerDto.getNic());
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(ReservationCancelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // search Package
    private void searchPackage() {
        String packId = txtPackageID.getText();
        try {
            PackageDto packageDto = packageController.getPackage(packId);
            if (packageDto != null) {
                PackDetaillbl.setText(packageDto.getPackageId() + "   |   " + packageDto.getName() + "   |   " + packageDto.getPrice());
            } else {
                JOptionPane.showMessageDialog(this, "Package Not Found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(ReservationCancelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
